<template>
    <button 
        class="
            px-8
            py-2
            rounded-2xl
            cursor-pointer
            hover:shadow-lg
            hover:shadow-blue-violet-light
            transition-shadow
            font-bold
            text-xl
            "><slot></slot></button>
</template>